steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'build', '--platform', 'linux/amd64', '-t', 'gcr.io/testing-app-344604/app-test3', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/testing-app-344604/app-test3']